### ISSUE TITLE
СхемаБД

### ISSUE THREAD

**Issue by RexuMiller** [RexuMiller/auto-notification-system#3]

**Comment by RexuMiller** [comment]
Примерная схема БД
[СхебаБД.docx](https://github.com/RexuMiller/auto-notification-system/files/2416952/default.docx)

**Comment by wldmr-key** [comment]
Проблемы составления схемы напрямую связаны с проблемами описания предметной области. И что это за странное оформление схемы? см. лекции и методичку!
